version: 0.2
env:
  shell: bash
phases:
  build:
    commands:
      - echo Build started on `date`
      # Running database migrations tasks.
      - aws ecs run-task 
        --launch-type FARGATE 
        --cluster ${ECS_CLUSTER} 
        --task-definition ${ECS_TASK_DEFINITION}
        --platform-version "1.4.0"
        --started-by "codebuild"
        --network-configuration 
          "awsvpcConfiguration = {
            subnets = [${ECS_SUBNETS_IDS}],
            securityGroups=[${ECS_SECURITY_GROUPS}]
          }"
